name: ISSUE_COMMENT_DOWNLOADER

on: issue_comment

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ github.event.issue.id == 842467443 }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          env
          echo "Comment on issue title is #${{ github.event.issue.title }}"
          echo "Comment on issue number is #${{ github.event.issue.number }}"
          echo "Comment on issue url is #${{ github.event.issue.url }}"
          echo "Comment on issue id is #${{ github.event.issue.id }}"
          echo "Comment on commer body is #${{ github.event.comment.body }}"