name: ISSUE_COMMENT_DOWNLOADER

on: 
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    # This job only runs for issue comments
    name: Issue Downloader
    if: ${{ github.event.issue.id == 842467443 &&  github.event.comment.user.login == 'wertycn' }}
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 执行下载  
        run: |
          ls
          echo "download url is ${{ github.event.comment.body }}"
          mkdir downloader
          cd downloader
          wget ${{ github.event.comment.body }}
          FILE_NAME=`ls`
          chmod 765 -R ./bin/
          ./bin/htool-cli cos --method upload --key downloader/${FILE_NAME} --path ./${FILE_NAME} --sk ${{ secrets.TENCENT_COS_SK }} --ak  ${{ secrets.TENCENT_COS_AK }} --url ${{ secrets.TENCENT_COS_URL }}
          echo "result path is /downloader/${FILE_NAME}"
